### ISSUE TITLE
Rolled mission back to testing level....need help getting ready.

### ISSUE THREAD

**Issue by coachwn** [Task-Force-Red/Operation-Willing-Disaster#32]
In order to do the mission the way I wanted to make it happen I am rolling it back to V6 from earlier on to allow for revamp and restructure of forces. Only utilizing 26 ground slots but opened up to 8 aviation slots. The remaining slots will function as IDAP once that faction is ready to roll with release.

**Comment by Jmaster9999** [comment]
I updated the loadouts and loadout controller to the latest versions script-side however we still need to replace the old unit-init lines with the new code.

**Comment by Jmaster9999** [comment]
If you can send me the updated modlist I can set everything up on the server side and get the testing server up.

**Comment by coachwn** [comment]
It's already setup server side for testing

**Comment by Jmaster9999** [comment]
It's missing JBAD_defines (Lythium apparently requires them). The mission enters a crash loop. If they are included in Lythium it may be possible that Lythium didn't download correctly. In which case I can redownload it.

**Comment by coachwn** [comment]
Lythium is not there....youare thinking about old mission that was up on the other projects list. Lythium is a no go for ALiVE at this time. It has several badly indexed areas and I am too lazy to deal with custom objectives...I just want crap to work.

**Comment by Jmaster9999** [comment]
Ah got it.

**Comment by coachwn** [comment]
Closing this issue
