### ISSUE TITLE
IEDs that AI are planting are not working.

### ISSUE THREAD

**Issue by Jebudiah** [Task-Force-Red/Operation-Willing-Disaster#39]
IED1, IED2, IED3, IED4 tested and do not appear to work. They can not be set off either by proximity or even with Zues lightning.

They might need to be set as an IED class.

**Comment by coachwn** [comment]
Will take a look at it and see what I can come up with.

**Comment by coachwn** [comment]
Updated mission file and added some tweaks...lets see what happens now.
